version: "3.2"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - type: bind
        source: /tmp/postgres
        target: /var/lib/postgresql/data
